dataset: "ADE20K"
batch_size: 2
epochs: 40
learning_rate: 6e-5
arch:
  B0:
    K: [7, 3, 3, 3]
    S: [4, 2, 2, 2]
    P: [3, 1, 1, 1]
    C: [32, 64, 160, 256]
    R: [8, 4, 2, 1]
    N: [1, 2, 5, 8]
    E: [8, 8, 4, 4]
    L: [2, 2, 2, 2]

  B1:
    K: [7, 3, 3, 3]
    S: [4, 2, 2, 2]
    P: [3, 1, 1, 1]
    C: [32, 64, 160, 256]
    R: [8, 4, 2, 1]
    N: [1, 2, 5, 8]
    E: [8, 8, 4, 4]
    L: [2, 2, 2, 2]

  B2: 
    K: [7, 3, 3, 3]
    S: [4, 2, 2, 2]
    P: [3, 1, 1, 1]
    C: [32, 64, 160, 256]
    R: [8, 4, 2, 1]
    N: [1, 2, 5, 8]
    E: [8, 8, 4, 4]
    L: [2, 2, 2, 2]

  B3:
    K: [7, 3, 3, 3]
    S: [4, 2, 2, 2]
    P: [3, 1, 1, 1]
    C: [32, 64, 160, 256]
    R: [8, 4, 2, 1]
    N: [1, 2, 5, 8]
    E: [8, 8, 4, 4]
    L: [2, 2, 2, 2]

  B4:
    K: [7, 3, 3, 3]
    S: [4, 2, 2, 2]
    P: [3, 1, 1, 1]
    C: [32, 64, 160, 256]
    R: [8, 4, 2, 1]
    N: [1, 2, 5, 8]
    E: [8, 8, 4, 4]
    L: [2, 2, 2, 2]

  B5:
    K: [7, 3, 3, 3]
    S: [4, 2, 2, 2]
    P: [3, 1, 1, 1]
    C: [32, 64, 160, 256]
    R: [8, 4, 2, 1]
    N: [1, 2, 5, 8]
    E: [8, 8, 4, 4]
    L: [2, 2, 2, 2]
